<?php

/**
 * Class pwp_daily_constants
 */
class pwp_daily_constants {

  /** @var array */
  const TEAM_KEYS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];

  /** @var string  */
  const DAILY_NO_CONTEST_KEY = '-1';

  /** @var string  */
  const DAILY_NO_CONTEST_TRUE = '1';

  /** @var string  */
  const DAILY_NO_CONTEST_FALSE = '0';

  /** @var string  */
  const DAILY_GAME_DATE_VARIABLE = 'pwp_daily_last_game';

  /** @var string  */
  const DAILY_GAME_VARIABLE = 'pwp_daily_game';
}
